/**
 * Brand icons, imported by name so the bundler drops the ~3,400 we do not use.
 *
 * They ship inside the app rather than being hotlinked from a CDN: the version
 * is locked by package.json, so an upstream rename can never turn these into
 * 404s at runtime. Adding a skill means adding its import here.
 *
 * Note: Simple Icons has removed some brands (Adobe, AWS, LinkedIn among them)
 * over trademark policy, so those names do not exist. `SkillIcon` falls back to
 * a lettered badge for any name it cannot resolve.
 */
import {
  SiBlender,
  SiCloudflare,
  SiCss,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithubactions,
  SiGraphql,
  SiGreensock,
  SiHtml5,
  SiJavascript,
  SiKubernetes,
  SiLinux,
  SiLottiefiles,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSketch,
  SiStorybook,
  SiTailwindcss,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
} from 'react-icons/si'

export const SKILL_ICONS = {
  SiBlender,
  SiCloudflare,
  SiCss,
  SiDocker,
  SiExpress,
  SiFigma,
  SiFirebase,
  SiFramer,
  SiGit,
  SiGithubactions,
  SiGraphql,
  SiGreensock,
  SiHtml5,
  SiJavascript,
  SiKubernetes,
  SiLinux,
  SiLottiefiles,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPostman,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiSketch,
  SiStorybook,
  SiTailwindcss,
  SiTerraform,
  SiThreedotjs,
  SiTypescript,
  SiVercel,
  SiVite,
  SiVitest,
  SiVuedotjs,
}
